import json, os, subprocess, random
from moviepy.config import change_settings
from moviepy.editor import *
import moviepy.video.fx.all as vfx
from PIL import Image
import numpy as np

# System Font Fix from our previous session
FONT_PATH = "Cinzel-Bold" 

if not hasattr(Image, 'ANTIALIAS'): Image.ANTIALIAS = Image.LANCZOS
if os.name == 'posix': change_settings({"IMAGEMAGICK_BINARY": "/usr/bin/convert"})

def apply_ken_burns(clip, duration):
    """Adds a cinematic zoom-in effect to static images."""
    return clip.resize(lambda t: 1 + 0.04 * t).set_duration(duration)

def render(plan_file):
    with open(plan_file, 'r') as f: data = json.load(f)
    print(f"🔱 TITAN RENDERING: {data['file_name']}")

    # 1. Generate High-Emotion Voice
    subprocess.run(["edge-tts", "--voice", "en-US-ChristopherNeural", "--text", data['script_text'], "--write-media", "v.mp3"])
    voice = AudioFileClip("v.mp3")
    duration = voice.duration + 1.5
    
    # 2. Base Cinematic Layers
    # Dark background + Mystical Music
    bg = ColorClip((1080, 1920), (10, 5, 20), duration=duration)
    music = AudioFileClip("assets/music/mystical_bg.mp3").volumex(0.15).set_duration(duration)
    
    clips = [bg]
    
    # 3. Dynamic Image Layer (The 'Video' Feel)
    imgs = data.get('images', [])
    if imgs:
        num_imgs = len(imgs)
        time_per_img = duration / num_imgs
        for i, path in enumerate(imgs):
            if os.path.exists(path):
                img_clip = ImageClip(path).resize(width=1100).set_pos("center")
                # Apply the Motion Engine
                img_clip = apply_ken_burns(img_clip, time_per_img)
                img_clip = img_clip.set_start(i * time_per_img).crossfadein(1).crossfadeout(1)
                clips.append(img_clip)

    # 4. KINETIC SUBTITLES (Peak Level Typography)
    # We split the script into punchy segments for the screen
    words = data['script_text'].split()
    group_size = 3 # 3 words at a time for maximum 'viral' retention
    segments = [" ".join(words[i:i+group_size]) for i in range(0, len(words), group_size)]
    
    seg_duration = duration / len(segments)
    for i, seg in enumerate(segments):
        txt = TextClip(seg.upper(), fontsize=100, color='#FFD700', font=FONT_PATH, 
                       stroke_color='black', stroke_width=3, method='caption', size=(950, None))
        txt = txt.set_start(i * seg_duration).set_duration(seg_duration).set_pos(('center', 1000))
        # Add a slight pop-in animation
        txt = txt.resize(lambda t: 1 + 0.1 * t).set_opacity(lambda t: min(1, 5*t))
        clips.append(txt)

    # 5. Professional Branding Overlay
    website = TextClip("thezodiacvault.kesug.com", fontsize=40, color='cyan', font=FONT_PATH)
    clips.append(website.set_pos(('center', 1750)).set_duration(duration).set_opacity(0.6))

    # 6. Final Export
    final = CompositeVideoClip(clips).set_audio(CompositeAudioClip([voice, music]))
    output_path = os.path.join("output_videos", data['title'].replace(" ", "_") + ".mp4")
    final.write_videofile(output_path, fps=24, preset='ultrafast', threads=4)

if __name__ == "__main__":
    if not os.path.exists("output_videos"): os.makedirs("output_videos")
    # Render every plan generated by the Master Brain
    plans = [f for f in os.listdir('.') if f.startswith('plan_')]
    for p in plans: render(p)
